### ISSUE TITLE
Some errors when creating a server

### ISSUE THREAD

**Issue by zZOGZz** [Qbox-project/txAdminRecipe#16]
Please take a look at what happens when the recipe is deployed:

![2023-03-13](https://user-images.githubusercontent.com/94694368/224811701-89fb79a5-9a71-4366-825c-b723e7117a10.png)

**Comment by YvanCywan** [comment]
I've deployed the recipe on my local machine and seem to have 0 issues regarding this, so the issue seems far more to do with what is going on with your server/local PC.

I would recommend installing a fresh copy of ox_inventory manually and see if that helps considering the errors that are displaying in your console.

In the future, it might be more beneficial to provide the txAdmin recipe deployment logs rather than just the script errors that it results in.
